version: "3.9"

services:

  discord_bot:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    container_name: discord_bot
    image: discord_bot
    env_file:
    - ./docker/python/.env
    volumes:
    - ./code:/code

networks:
  default:
    name: discord_bot_network